### PR TITLE
Fix SELinux in service.sh

### PR DESCRIPTION
**Pull request by crashoverride1995**

### CODE REVIEW

**Comment by MarcAnt01** [comment]
Thanks, will take a look at the additional modification you have done to sepolicy stuff, can you explain what they consist of?

**Comment by crashoverride1995** [comment]
The sepolicy modifications are there in the original module itself by 3liteking148, the one which he released with SELinux fix. They basically patch the sepolicy of the ROM to allow the modified libs to work as intended.

**Comment by MarcAnt01** [comment]
I cannot see that in the latest version available in Celsoazevedo

**Comment by MarcAnt01** [comment]
Is the version on Celsoazevedo the latest @crashoverride1995

**Comment by crashoverride1995** [comment]
No the latest one was posted on the XDA thread the version on Celsoazevedo doesn't include the SELinux Enforcing fix.
Latest version:https://forum.xda-developers.com/showpost.php?p=79279542&postcount=6857

**Comment by MarcAnt01** [comment]
> No the latest one was posted on the XDA thread the version on Celsoazevedo doesn't include the SELinux Enforcing fix.
> Latest version:https://forum.xda-developers.com/showpost.php?p=79279542&postcount=6857

Thanks for letting me know, wasn't aware of that. Will merge as soon as I have tested if it doesn't cause issues on Roms with SELinux permissive, otherwise I'll have to move the content to a custom prop

**Pull request merged**
