### PR TITLE
fix device and api check and remove recursive flag from cp

### PR DESCRIPTION
**Pull request by JohnFawkes**
Signed-off-by: JohnFawkes <33303104+JohnFawkes@users.noreply.github.com>

### CODE REVIEW

**Review by MarcAnt01 — COMMENTED** [review]
Why using -le ? The module is for Oreo and Pie

**Comment by JohnFawkes** [comment]
> Why using -le ? The module is for Oreo and Pie

you had it to abort on -le 26. 

  if [ "$API" -ge 26 ]; then
    break
  else
    abort "Your Android version doesn't require this fix"
  fi

**Comment by MarcAnt01** [comment]
Ah, you are right, but why isn't the `cancel` function added to `on_install`?

**Comment by JohnFawkes** [comment]
> Ah, you are right, but why isn't the `cancel` function added to on_install?

its a seperate function. its basically abort but it has fixes for magisk less than 18 where it used a magisk.img

**Comment by MarcAnt01** [comment]
> Ah, you are right, but why isn't the cancel function added to on_install?
> 
> its a seperate function. its basically abort but it has fixes for magisk less than 18 where it used a magisk.img

Thanks for the explanation

**Comment by MarcAnt01** [comment]
My device isn't detected properly, build.prop value is ro.product.device = oneplus3
image

**Comment by MarcAnt01** [comment]
Now, I have moved to Unity and the built-in device checks works properly, thanks anyway for the effort you've put on that

**Pull request closed without merging**
